---
name: "StackForms test around required values"
canonical: "stack-test-required"
version: "4"
description: |
  This stack is just a way of testing required values.
author: "Cycloid"
config:
  default:
    name: "Default"
    description: "Default pipeline usecase"
    pipeline:
      pipeline:
        path: "pipeline/pipeline.yml"
      variables:
        path: "pipeline/variables.sample.yml"
        destination: "($ .config_root $)/pipeline/variables.yml"
