---
version: "2"
use_cases:
- name: "default"
  sections:
  - name: "section"
    groups:
    - name: "group"
      technologies:
      - "pipeline"
      vars:
      - name: "not_required"
        key: "not_required"
        widget: "simple_text"
        type: "string"
      - name: "not_required_with_default"
        key: "not_required_with_default"
        widget: "simple_text"
        type: "string"
        default: "i_have_a_default"
      - name: "required"
        key: "required"
        widget: "simple_text"
        type: "string"
        required: true
      - name: "required_with_default"
        key: "required"
        widget: "simple_text"
        type: "string"
        required: true
        default: "i_have_a_default"
