jobs:
- name: job-hello-world
  build_logs_to_retain: 3
  plan:
  - task: hello-world
    config:
        platform: linux
        image_resource:
            type: registry-image
            source: {repository: busybox, tag: latest}
        run:
          path: /bin/sh
          args:
          - -ec
          - |
            echo text_area
            echo $(text_area)
            echo text_area_required
            echo $(text_area_required)
            echo dropdown_arrays
            echo $(dropdown_arrays)
            echo dropdown
            echo $(dropdown)
            echo dropdown_required
            echo $(dropdown_required)
            echo dropdown_required_default
            echo $(dropdown_required_default)
            echo auto_complete
            echo $(auto_complete)
            echo auto_complete_required
            echo $(auto_complete_required)
            echo auto_complete_required_default_string
            echo $(auto_complete_required_default_string)
            echo auto_complete_required_default_array
            echo $(auto_complete_required_default_array)
        params:
          text_area: ((text_area))
          text_area_required: ((text_area_required))
          dropdown_arrays: ((dropdown_arrays))
          dropdown: ((dropdown))
          dropdown_required: ((dropdown_required))
          dropdown_required_default: ((dropdown_required_default))
          auto_complete: ((auto_complete))
          auto_complete_required: ((auto_complete_required))
          auto_complete_required_default_string: ((auto_complete_required_default_string))
          auto_complete_required_default_array: ((auto_complete_required_default_array))

