---
name: "Pipeline testing"
canonical: "stack-test-pipeline"
version: "4"
description: |
  Pipelines related test in cycloid
author: "Cycloid"

config:
  default:
    name: "Default"
    description: "Default pipeline usecase"
    pipeline:
      pipeline:
        path: "pipeline/pipeline.yml"
      variables:
        path: "pipeline/variables.sample.yml"
        destination: "($ .config_root $)/pipeline/variables.yml"
    custom:
      var_path: "($ .config_root $)/vars.json"
      templates:
      - paths:
        - "test.yaml"
        destination: "($ .config_root $)/"
