---
version: "2"
use_cases:
- name: "default"
  sections:
  - name: "section"
    groups:
    - name: "group"
      technologies:
      - "pipeline"
      vars:
      - name: "Var"
        key: "var"
        widget: "text_area"
        type: "map"
      - name: "Var"
        key: "some"
        widget: "text_area"
        type: "string"
