---
version: "2"
use_cases:
- name: default
  sections:
  - name: AWS Network Landing Zone
    groups:
    - name: AWS Cloud Configuration
      technologies: [pipeline]
      vars:
      - name: "AWS account"
        description: "The AWS account where to deploy the infrastructure. It contains access key and secret key."
        key: aws_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - aws
        type: string
        default: "((aws))"
        required: true
      - name: "AWS region"
        description: "AWS region to use for Terraform."
        key: aws_region
        widget: auto_complete
        type: string
        values_ref: https://cycloid-demo-stackforms-values.s3.eu-west-1.amazonaws.com/aws-regions.json
        default: eu-west-1
        validations: 
        - regexp: "^[a-z]{2}-[a-z]+-\\d+$" 
          error_message: "Please enter a valid AWS region such as us-east-1"
        required: true

    - name: Network Configuration
      technologies: [terraform]
      vars:
      - name: "VPC CIDR"
        description: "The CIDR of the VPC to create."
        key: module.network.vpc_cidr
        widget: simple_text
        type: string
        default: "10.0.0.0/16"
        validations: 
        - regexp: "^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\/[0-9]{1,2}$" 
          error_message: "Please enter a valid CIDR such as 10.0.0.0/16"
        required: true
      - name: "Public Subnet CIDR"
        description: "The CIDR of the public subnet."
        key: module.network.vpc_public_subnet
        widget: simple_text
        type: string
        default: "10.0.0.0/24"
        validations: 
        - regexp: "^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\/[0-9]{1,2}$" 
          error_message: "Please enter a valid CIDR such as 10.0.0.0/24"
        required: true
      - name: "Private Subnet CIDR"
        description: "The CIDR of the private subnet."
        key: module.network.vpc_private_subnet
        widget: simple_text
        type: string
        default: "10.0.1.0/24"
        validations: 
        - regexp: "^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\/[0-9]{1,2}$" 
          error_message: "Please enter a valid CIDR such as 10.0.0.0/24"
        required: true
      - name: "NAT Gateway"
        description: "Whether to deploy a NAT gateway or not."
        key: module.network.nat_gateway
        widget: switch
        type: boolean
        default: false
        required: true

    - name: Key Pair
      technologies: [terraform]
      vars:
      - name: "SSH Public key"
        description: "The public SSH key to provision to newly created instances."
        key: module.key_pair.key_pair_public
        widget: simple_text
        type: string
        default: ""
        validations: 
        - regexp: "^ssh-[a-z]+\\s+[A-Za-z0-9+/=]+\\s[^\\s]+$"
          error_message: "Please enter a valid public SSH key"
        required: true