---
name: "CLI e2e stackforms tests 2"
canonical: "stack-e2e-stackforms-2"
description: |
  This stack is made for testing stackforms value update via the CLI.
keywords:
- "concourse"
- "dummy"
author: "Cycloid"
image: |
  https://raw.githubusercontent.com/cycloid-community-catalog/stack-dummy/master/icon.png
technologies:
- technology: "concourse"
  version: "n/a"
- technology: "busybox"
  version: "n/a"

config:
  default:
    name: "Default"
    description: "Default pipeline usecase"
    pipeline:
      pipeline:
        path: "pipeline/pipeline.yml"
      variables:
        path: "pipeline/variables.sample.yml"
        destination: "($ .project $)/pipeline/variables-($ .environment $).yml"
